from __future__ import annotations

import math
from collections import Counter
from typing import Any, Iterable, Mapping

from .types import HarnessRun


ROUND_EXPERIMENT_SCHEMA_VERSION = "scientific_harness_round_experiment.v1"
DEFAULT_ROUND_COUNTS = (1, 3, 5)


def parse_round_counts(
    value: str | Iterable[int] | None = None,
    *,
    available_rounds: int | None = None,
    default: tuple[int, ...] = DEFAULT_ROUND_COUNTS,
) -> tuple[int, ...]:
    """Parse and validate prefix lengths for a round-count experiment.

    ``one-shot`` is represented by one round.  Counts are interpreted as
    prefixes of the same proposal stream, so every protocol can be replayed
    from one input artifact without generating new candidates.
    """

    raw: Iterable[int]
    if value is None:
        raw = default
    elif isinstance(value, str):
        text = value.strip().lower()
        if text in {"", "default"}:
            raw = default
        elif text in {"one-shot", "oneshot", "one"}:
            raw = (1,)
        else:
            parts = [part.strip() for part in text.split(",") if part.strip()]
            if not parts:
                raise ValueError("round counts must contain at least one positive integer")
            try:
                raw = tuple(int(part) for part in parts)
            except ValueError as error:
                raise ValueError("round counts must be comma-separated positive integers") from error
    else:
        raw = value

    counts: list[int] = []
    for item in raw:
        try:
            count = int(item)
        except (TypeError, ValueError) as error:
            raise ValueError("round counts must be comma-separated positive integers") from error
        if count < 1:
            raise ValueError("round counts must be positive")
        if available_rounds is not None and count > available_rounds:
            raise ValueError(f"requested {count} rounds but input contains only {available_rounds}")
        if count not in counts:
            counts.append(count)
    if not counts:
        raise ValueError("round counts must contain at least one positive integer")
    return tuple(counts)


def _as_run_dict(run: HarnessRun | Mapping[str, Any]) -> Mapping[str, Any]:
    if isinstance(run, HarnessRun):
        return run.to_dict()
    if not isinstance(run, Mapping):
        raise TypeError("run must be a HarnessRun or mapping")
    return run


def _as_float(value: Any) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)) and math.isfinite(float(value)):
        return float(value)
    return None


def _record_gain(record: Mapping[str, Any]) -> float | None:
    # The role output is authoritative after post-compute evaluation.  The
    # candidate validation field is accepted for replay artifacts generated by
    # external executors that do not rerun the role layer.
    outputs = record.get("role_outputs") or {}
    planner = outputs.get("validation_planner") if isinstance(outputs, Mapping) else None
    gain = _as_float(planner.get("marginal_gain")) if isinstance(planner, Mapping) else None
    if gain is not None:
        return gain
    candidate = record.get("candidate") or {}
    validation = candidate.get("validation") if isinstance(candidate, Mapping) else None
    if isinstance(validation, Mapping):
        gain = _as_float(validation.get("marginal_gain"))
        if gain is None:
            delta = _as_float(validation.get("marginal_validation_delta"))
            if delta is not None:
                gain = -delta
    return gain


def _novelty_verdict(record: Mapping[str, Any]) -> str | None:
    outputs = record.get("role_outputs")
    if not isinstance(outputs, Mapping):
        return None
    novelty = outputs.get("novelty_auditor")
    if not isinstance(novelty, Mapping):
        return None
    verdict = novelty.get("verdict")
    return str(verdict) if verdict in {"duplicate", "novel"} else None


def _record_was_accepted(record: Mapping[str, Any]) -> bool:
    """Whether routing accepted this candidate for the validation path."""

    jev = record.get("jev")
    if isinstance(jev, Mapping) and jev.get("recommendation") == "compute_validate":
        return True
    candidate = record.get("candidate")
    return isinstance(candidate, Mapping) and candidate.get("retained") is True


def _feedback_flag(candidate: Mapping[str, Any]) -> bool | None:
    """Read an explicit feedback-use annotation when one is present.

    Candidate generators can set one of these stable keys.  We deliberately do
    not infer use from text, because that would turn an audit metric into a
    prompt-dependent heuristic.
    """

    for key in ("feedback_used", "uses_previous_feedback", "used_feedback"):
        value = candidate.get(key)
        if isinstance(value, bool):
            return value
    for key in ("revision_of", "revised_from", "prior_candidate_ids", "feedback_refs"):
        value = candidate.get(key)
        if value:
            return True
    return None


def _is_revision(candidate: Mapping[str, Any]) -> bool:
    """Whether the generator explicitly links this candidate to a prior one."""

    return any(candidate.get(key) for key in ("revision_of", "revised_from", "parent_id"))


def _oracle_label(candidate: Mapping[str, Any], oracle_key: str) -> bool | None:
    value = candidate.get(oracle_key)
    if isinstance(value, bool):
        return value
    oracle = candidate.get("oracle")
    if isinstance(oracle, Mapping) and isinstance(oracle.get(oracle_key), bool):
        return bool(oracle[oracle_key])
    return None


def compute_round_metrics(
    run: HarnessRun | Mapping[str, Any],
    *,
    target_gain: float = 0.0,
    oracle_key: str = "useful",
) -> dict[str, Any]:
    """Compute round-wise progress metrics from one harness replay.

    Gains are positive when adding a candidate improves validation (the role
    layer already converts ``candidate_mae - current_mae`` to a positive gain).
    Test/OOD values are never required and are ignored if present in the
    artifact.  Oracle recall metrics are emitted only when candidates carry an
    explicit boolean ``useful`` (or ``oracle.useful``) label.
    """

    payload = _as_run_dict(run)
    rounds = payload.get("rounds") or []
    if not isinstance(rounds, list):
        raise ValueError("run.rounds must be a list")

    round_metrics: list[dict[str, Any]] = []
    total_records = 0
    total_positive = 0
    cumulative_gain = 0.0
    total_accepted_positive = 0
    cumulative_accepted_gain = 0.0
    curve: list[dict[str, float | int]] = [{"round": 0, "cumulative_positive_gain": 0.0}]
    accepted_curve: list[dict[str, float | int]] = [{"round": 0, "cumulative_positive_gain": 0.0}]
    all_decisions: Counter[str] = Counter()
    feedback_observed = 0
    feedback_used = 0
    feedback_unknown = 0
    useful_total = 0
    useful_accepted = 0
    useful_rejected = 0
    duplicate_total = 0
    duplicate_avoided = 0
    revision_total = 0
    revision_success = 0
    failure_counts: Counter[str] = Counter()

    for index, round_row in enumerate(rounds, start=1):
        if not isinstance(round_row, Mapping):
            raise ValueError("each run round must be an object")
        records = round_row.get("records") or []
        if not isinstance(records, list):
            raise ValueError("round.records must be a list")
        gains = [gain for record in records if isinstance(record, Mapping) for gain in [_record_gain(record)] if gain is not None]
        positive = [gain for gain in gains if gain > target_gain]
        accepted_gains = [
            gain for record in records if isinstance(record, Mapping) and _record_was_accepted(record)
            for gain in [_record_gain(record)] if gain is not None
        ]
        accepted_positive = [gain for gain in accepted_gains if gain > target_gain]
        decisions = Counter()
        round_feedback_observed = 0
        round_feedback_used = 0
        round_feedback_unknown = 0
        round_useful_total = 0
        round_useful_accepted = 0
        round_useful_rejected = 0
        round_duplicate_total = 0
        round_duplicate_avoided = 0
        round_revision_total = 0
        round_revision_success = 0
        round_failure_counts: Counter[str] = Counter()
        for record in records:
            if not isinstance(record, Mapping):
                continue
            jev = record.get("jev") or {}
            recommendation = jev.get("recommendation") if isinstance(jev, Mapping) else None
            if recommendation:
                decisions[str(recommendation)] += 1
                all_decisions[str(recommendation)] += 1
            candidate = record.get("candidate") or {}
            if not isinstance(candidate, Mapping):
                continue
            # A first round has no prior feedback by construction.  Exclude
            # it from the denominator so the rate measures actual feedback
            # uptake rather than penalising one-shot candidates.
            if index > 1:
                feedback = _feedback_flag(candidate)
                if feedback is not None:
                    round_feedback_observed += 1
                    if feedback:
                        round_feedback_used += 1
                else:
                    round_feedback_unknown += 1
            verdict = _novelty_verdict(record)
            if verdict is not None:
                round_duplicate_total += 1
                if verdict == "novel":
                    round_duplicate_avoided += 1
            useful = _oracle_label(candidate, oracle_key)
            # The oracle denominator is the explicitly useful subset; a
            # ``useful: false`` label is a known negative and is not part of
            # useful-candidate recall or false-rejection.
            if useful is True:
                round_useful_total += 1
                if recommendation == "compute_validate":
                    round_useful_accepted += 1
                else:
                    round_useful_rejected += 1
            if _is_revision(candidate):
                round_revision_total += 1
                gain = _record_gain(record)
                if gain is not None and gain > target_gain:
                    round_revision_success += 1
            execution = candidate.get("execution")
            failure_code = execution.get("failure_code") if isinstance(execution, Mapping) else None
            if not failure_code:
                outputs = record.get("role_outputs")
                feasibility = outputs.get("feasibility_auditor") if isinstance(outputs, Mapping) else None
                failure_code = feasibility.get("failure_code") if isinstance(feasibility, Mapping) else None
            if failure_code:
                round_failure_counts[str(failure_code)] += 1
        total_records += len(records)
        total_positive += len(positive)
        cumulative_gain += sum(gain for gain in positive)
        total_accepted_positive += len(accepted_positive)
        cumulative_accepted_gain += sum(accepted_positive)
        feedback_observed += round_feedback_observed
        feedback_used += round_feedback_used
        feedback_unknown += round_feedback_unknown
        useful_total += round_useful_total
        useful_accepted += round_useful_accepted
        useful_rejected += round_useful_rejected
        duplicate_total += round_duplicate_total
        duplicate_avoided += round_duplicate_avoided
        revision_total += round_revision_total
        revision_success += round_revision_success
        failure_counts.update(round_failure_counts)
        curve.append({"round": index, "cumulative_positive_gain": cumulative_gain})
        accepted_curve.append({"round": index, "cumulative_positive_gain": cumulative_accepted_gain})
        round_metrics.append({
            "round_id": round_row.get("round_id", round_row.get("round", index)),
            "candidate_count": len(records),
            "decision_counts": dict(sorted(decisions.items())),
            "measured_gain_count": len(gains),
            "positive_gain_count": len(positive),
            "positive_gain_rate": len(positive) / len(gains) if gains else None,
            "mean_marginal_gain": sum(gains) / len(gains) if gains else None,
            "sum_positive_gain": sum(positive) if positive else 0.0,
            "cumulative_positive_gain": cumulative_gain,
            "accepted_gain_count": len(accepted_gains),
            "positive_accepted_gain_count": len(accepted_positive),
            "sum_positive_accepted_gain": sum(accepted_positive) if accepted_positive else 0.0,
            "cumulative_positive_accepted_gain": cumulative_accepted_gain,
            "feedback_observed_count": round_feedback_observed,
            "feedback_used_count": round_feedback_used,
            "feedback_unknown_count": round_feedback_unknown,
            "duplicate_count": sum(1 for record in records if isinstance(record, Mapping) and _novelty_verdict(record) == "duplicate"),
            "duplicate_avoidance_rate": round_duplicate_avoided / round_duplicate_total if round_duplicate_total else None,
            "revision_count": round_revision_total,
            "revision_success_count": round_revision_success,
            "revision_success_rate": round_revision_success / round_revision_total if round_revision_total else None,
            "failed_candidate_count": sum(round_failure_counts.values()),
            "failure_code_counts": dict(sorted(round_failure_counts.items())),
        })

    auc = 0.0
    for left, right in zip(curve, curve[1:]):
        auc += (float(left["cumulative_positive_gain"]) + float(right["cumulative_positive_gain"])) / 2.0
    accepted_auc = 0.0
    for left, right in zip(accepted_curve, accepted_curve[1:]):
        accepted_auc += (float(left["cumulative_positive_gain"]) + float(right["cumulative_positive_gain"])) / 2.0
    final_gain = cumulative_gain
    metrics: dict[str, Any] = {
        "schema_version": ROUND_EXPERIMENT_SCHEMA_VERSION,
        "round_count": len(round_metrics),
        "candidate_count": total_records,
        "decision_counts": dict(sorted(all_decisions.items())),
        "measured_gain_count": sum(item["measured_gain_count"] for item in round_metrics),
        "positive_gain_count": total_positive,
        "positive_gain_rate": total_positive / sum(item["measured_gain_count"] for item in round_metrics) if sum(item["measured_gain_count"] for item in round_metrics) else None,
        "final_cumulative_positive_gain": final_gain,
        "discovery_curve": curve,
        "discovery_curve_auc": auc,
        "discovery_curve_auc_per_round": auc / len(round_metrics) if round_metrics else None,
        "accepted_positive_gain_count": total_accepted_positive,
        "final_cumulative_positive_accepted_gain": cumulative_accepted_gain,
        "accepted_discovery_curve": accepted_curve,
        "accepted_discovery_curve_auc": accepted_auc,
        "accepted_discovery_curve_auc_per_round": accepted_auc / len(round_metrics) if round_metrics else None,
        "feedback_use_rate": feedback_used / feedback_observed if feedback_observed else None,
        "feedback_observed_count": feedback_observed,
        "feedback_used_count": feedback_used,
        "feedback_unknown_count": feedback_unknown,
        "duplicate_avoidance_rate": duplicate_avoided / duplicate_total if duplicate_total else None,
        "duplicate_count": duplicate_total - duplicate_avoided,
        "duplicate_audited_count": duplicate_total,
        "revision_count": revision_total,
        "revision_success_count": revision_success,
        "revision_success_rate": revision_success / revision_total if revision_total else None,
        "failed_candidate_count": sum(failure_counts.values()),
        "failure_code_counts": dict(sorted(failure_counts.items())),
        "oracle_key": oracle_key,
        "useful_candidate_count": useful_total if useful_total else None,
        "useful_candidate_recall": useful_accepted / useful_total if useful_total else None,
        "false_rejection_rate": useful_rejected / useful_total if useful_total else None,
        "rounds": round_metrics,
    }
    return metrics


def run_round_prefix_experiment(
    *,
    controller: Any,
    run_id: str,
    rounds: list[Any],
    round_counts: str | Iterable[int] | None = None,
    run_context: dict[str, Any] | None = None,
    oracle_key: str = "useful",
) -> dict[str, Any]:
    """Replay fixed proposal rounds at multiple prefix lengths.

    The same candidate artifact is used for every prefix; only the amount of
    feedback available to the controller changes.  This makes one-shot versus
    iterative comparisons reproducible and prevents accidental resampling.
    """

    counts = parse_round_counts(round_counts, available_rounds=len(rounds))
    protocols: list[dict[str, Any]] = []
    for count in counts:
        replay = controller.run(run_id=f"{run_id}.r{count}", rounds=rounds[:count], run_context=run_context or {})
        protocols.append({
            "rounds": count,
            "protocol": "one_shot" if count == 1 else "feedback_loop",
            "run": replay.to_dict(),
            "metrics": compute_round_metrics(replay, oracle_key=oracle_key),
        })
    return {
        "schema_version": ROUND_EXPERIMENT_SCHEMA_VERSION,
        "run_id": run_id,
        "round_counts": list(counts),
        "protocols": protocols,
        "warnings": [
            "Prefix replay compares fixed candidate streams; it does not regenerate model proposals for each round count.",
            "Validation gains are only counted when an execution feedback field is present.",
            "Oracle recall and false-rejection are emitted only for explicit candidate useful labels.",
        ],
    }
