FROM docker.m.daocloud.io/library/node:22-bookworm-slim AS build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci --registry=https://registry.npmmirror.com

COPY frontend ./
RUN npm run build

FROM docker.m.daocloud.io/library/nginx:1.27-alpine
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
